FROM gradle:jdk18-jammy as build
WORKDIR /app
COPY src/ src/
COPY build.gradle .
COPY MankianersTelegramSpringStarter/ MankianersTelegramSpringStarter/
COPY settings.gradle .
RUN gradle bootJar

FROM eclipse-temurin:18-jdk-jammy

ARG app_name='ToDoAssistant'
ENV app_name=${app_name}

WORKDIR /app
COPY --from=build /app/build/libs/*.jar ${app_name}.jar
EXPOSE 8080

RUN java -version

ENV springProfilesActive=''

ENTRYPOINT java -Dspring.profiles.active=${springProfilesActive} -Dtelegram.user.file=/app/data/telegram/users -jar /app/${app_name}.jar