name: Delete old releases

on:
  push:
    branches: [ "cleanUp" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: remove rc releases
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          user: mankianer
          type: container
          version-pattern: "^\\d+\\.\\d+\\.\\d+-rc\\.\\d+$"
          names: todoassistant3
          keep: 0
          dry-run: true