name: Delete old releases

on:
  push:
    branches: [ "cleanUp" ]

jobs:
  build:
    steps:
      - name: keep the latest 5 releases
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          user: mankianer
          type: container
          names: todoassistant3
          keep: 5
          version-pattern: 'latest'
          dry-run: true