name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run gradlew bootJar
        run: |
          ./gradlew bootJar
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_pi
          platforms: linux/arm64
          push: true
          tags: ghcr.io/mankianer/todoassistant3:arm64

      - name: Build the Docker image for amd64
        run: docker build . --file Dockerfile --tag ghcr.io/mankianer/todoassistant3:amd64
      - name: Push the Docker image for amd64
        run: docker push ghcr.io/mankianer/todoassistant3:amd64


