name: Docker Image CI - release candidate

on:
  pull_request:
    branches: [ "main" ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: run?
        run: docker buildx ls

      - name: build images
        run: |
          docker buildx  build . -t ghcr.io/mankianer/todoassistant3:arm64-rc --platform linux/arm64
          docker buildx  build . -t ghcr.io/mankianer/todoassistant3:amd64-rc --platform linux/amd64
          docker manifest create ghcr.io/mankianer/todoassistant3:rc ghcr.io/mankianer/todoassistant3:amd64-snapshot ghcr.io/mankianer/todoassistant3:arm64-rc

      - name: push images
        run: |
          docker push ghcr.io/mankianer/todoassistant3:arm64-rc
          docker push ghcr.io/mankianer/todoassistant3:amd64-rc
          docker manifest push ghcr.io/mankianer/todoassistant3:rc
