name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: run?
        run: docker buildx ls

      - name: build images
        run: |
          docker build . -t ghcr.io/{{ github.actor }}/{{ github.repository }}:arm64 --platform=linux/arm64
          docker build . -t ghcr.io/{{ github.actor }}/{{ github.repository }}:amd64 --platform=linux/amd64
          docker manifest create ghcr.io/{{ github.actor }}/{{ github.repository }}:latest ghcr.io/{{ github.actor }}/{{ github.repository }}:amd64 ghcr.io/{{ github.actor }}/{{ github.repository }}:arm64

      - name: push images
        run: |
          docker push ghcr.io/{{ github.actor }}/{{ github.repository }}:arm64 --platform=linux/arm64
          docker push ghcr.io/{{ github.actor }}/{{ github.repository }}:amd64 --platform=linux/amd64
          docker manifest push ghcr.io/{{ github.actor }}/{{ github.repository }}:latest
