name: Docker Image CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Login
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Set up env-variables
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
          if [ "${{ github.ref_name }}" == "main" ]; then
          export releaseTask=final
          elif [ "${{ github.ref_name }}" == "develop" ]; then
          export releaseTask=devSnapshot
          fi
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
          if [ "${{ github.base_ref }}" == "main" ]; then
          git checkout origin/${{ github.head_ref }}
          export releaseTask=candidate
          fi
          fi
          echo "releaseTask=${releaseTask}" >> $GITHUB_ENV
          
          if [ ${releaseTask} == "final" ] || [ ${releaseTask} == "candidate" ]; then
          echo "useLastTag=true" >> $GITHUB_ENV
          else
          echo "useLastTag=false" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: run?
        run: docker buildx ls

      - name: run build-container
        run: |
            docker run -d --name build -v ${PWD}:/home/gradle gradle:jdk18 gradle --foreground

      - name: create new version
        run: |
          export version=$(docker exec build sh -c "gradle -Dorg.ajoberstar.grgit.auth.actor='${{github.actor}}' -Dorg.ajoberstar.grgit.auth.username='GitHub Action' -Dorg.ajoberstar.grgit.auth.email='github-action@users.noreply.github.com' -Dorg.ajoberstar.grgit.auth.password='${{ secrets.GITHUB_TOKEN }}' properties ${{ env.releaseTask }} | grep ^version: | cut -d\":\" -f2- | xargs")
          echo "version=${version}" >> $GITHUB_ENV
          echo "versionImage=$(echo ${version} | sed -e 's/[^a-z|0-9|.|-]/-/g')" >> $GITHUB_ENV


      - name: build jar
        run: docker exec build gradle -Prelease.useLastTag=${{ env.useLastTag }} ${{env.releaseTask}} bootJar

      - name: build images
        run: |
          docker buildx  build . -t ${{env.registry}}/mankianer/todoassistant3:arm64-${{env.versionImage}} --platform linux/arm64
          docker buildx  build . -t ${{env.registry}}/mankianer/todoassistant3:amd64-${{env.versionImage}} --platform linux/amd64

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push images
        run: |
          docker push ${{env.registry}}/mankianer/todoassistant3:arm64-${{env.versionImage}}
          docker push ${{env.registry}}/mankianer/todoassistant3:amd64-${{env.versionImage}}

      - name: push image-manifest
        run: |
          docker manifest create ${{env.registry}}/mankianer/todoassistant3:${{env.versionImage}} ${{env.registry}}/mankianer/todoassistant3:amd64-${{env.versionImage}} ${{env.registry}}/mankianer/todoassistant3:arm64-${{env.versionImage}}
          docker manifest push ${{env.registry}}/mankianer/todoassistant3:${{env.versionImage}}

      - name: push latest image
        if: ${{ env.releaseTask == 'final' }}
        run: |
          docker manifest tag ${{env.registry}}/mankianer/todoassistant3:${{env.versionImage}} ${{env.registry}}/mankianer/todoassistant3:latest
          docker manifest push ${{env.registry}}/mankianer/todoassistant3:latest


  clean-images:
    needs: build
    name: Clean images
    runs-on: ubuntu-latest
    steps:
      - name: Clean - remove rc releases
        if: ${{ env.ref_name != 'main' }}
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          user: mankianer
          type: container
          version-pattern: "^(amd64-|arm64-)?\\d+\\.\\d+\\.\\d+-rc\\.\\d+$"
          names: todoassistant3
          keep: 5
      - name: Clean - remove devSnapshots releases
        if: ${{ env.ref_name != 'main' }}
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          user: mankianer
          type: container
          version-pattern: "^(amd64-|arm64-)?\\d+\\.\\d+\\.\\d+-dev\\.\\d+-.{7}$"
          names: todoassistant3
          keep: 5
      - name: Clean - keep last 10 releases
        if: ${{ env.ref_name == 'main' }}
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          user: mankianer
          type: container
          version-pattern: "^(amd64-|arm64-)?\\d+\\.\\d+\\.\\d+$"
          names: todoassistant3
          keep: 10
      - name: Clean - delete all other releases
        if: ${{ env.ref_name == 'main' }}
        uses: SmartsquareGmbH/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.GHCR_PAT }}
          user: mankianer
          type: container
          version-pattern: "^(?!((amd64-|arm64-)?\\d+\\.\\d+\\.\\d+$)).*"
          names: todoassistant3
          keep: 0