name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite:latest
          commands: |
            sudo apt-get install -yq docker
            docker build . --file Dockerfile --tag ghcr.io/mankianer/todoassistant3:arm64
            docker login -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }} ghcr.io 
            docker push ghcr.io/mankianer/todoassistant3:arm64    

  build-amd64:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: actions/checkout@v3
      - name: Build the Docker image for amd64
        run: docker build . --file Dockerfile --tag ghcr.io/mankianer/todoassistant3:amd64
      - name: Push the Docker image for amd64
        run: docker push ghcr.io/mankianer/todoassistant3:amd64


