name: Docker Image CI - snapshot

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      image_version: latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: run?
        run: docker buildx ls

      - name: build jar
        run: docker run --name build -v ${PWD}:/home/gradle gradle:jdk18 gradle final bootJar

      - name: build images
        run: |
          docker buildx  build . -t ${registry}/mankianer/todoassistant3:arm64 --platform linux/arm64
          docker buildx  build . -t ${registry}/mankianer/todoassistant3:amd64 --platform linux/amd64

      - name: push images
        run: |
          docker push ${registry}/mankianer/todoassistant3:arm64
          docker push ${registry}/mankianer/todoassistant3:amd64

      - name: push image-manifest
        run: |
          docker manifest create ${registry}/mankianer/todoassistant3:${image_version} ${registry}/mankianer/todoassistant3:amd64 ${registry}/mankianer/todoassistant3:arm64
          docker manifest push ${registry}/mankianer/todoassistant3:${image_version}
