name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        name: Build and Push the Docker image for aarch64
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04
          run: |
            docker build . --file Dockerfile --tag ghcr.io/mankianer/todoassistant3:aarch64
            docker push ghcr.io/mankianer/todoassistant3:aarch64

      - name: Build the Docker image for amd64
        run: docker build . --file Dockerfile --tag ghcr.io/mankianer/todoassistant3:amd64
      - name: Push the Docker image for amd64
        run: docker push ghcr.io/mankianer/todoassistant3:amd64


